version: '0.1'

services:
  mssql:
    container_name: mssql_server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "DevPass!Word"
    ports:
      - 1433:1433
    volumes:
      - ./data/mssql:/var/opt/mssql
  
  mosquitto:
    container_name: mosquitto_broker
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./data/mosquitto/config:/mosquitto/config
      - ./data/mosquitto/data:/mosquitto/data
      - ./data/mosquitto/log:/mosquitto/log