version: '0.1'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - 1433:1433
    volumes:
      - ./data/mssql/data:/var/opt/mssql
  
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data/mosquitto/data:/mosquitto/data
      - ./data/mosquitto/log:/mosquitto/log
  
  opcplc1:
    image: mcr.microsoft.com/iotedge/opc-plc:latest
    restart: unless-stopped
    hostname: opcplc1
    ports:
      - 50001:50000
      - 8081:8080
    command: >
      --aa
      --to
      --ph=opcplc1
      --pn=50000
      --sph
      --sn=5
      --sr=10
      --st=uint
      --fn=5
      --fr=1
      --ft=uint
      -v

  opcplc2:
    image: mcr.microsoft.com/iotedge/opc-plc:latest
    restart: unless-stopped
    hostname: opcplc2
    ports:
      - 50002:50000
      - 8082:8080
    command: >
      --aa
      --to
      --ph=opcplc2
      --pn=50000
      --sph
      --sn=5
      --sr=10
      --st=uint
      --fn=5
      --fr=1
      --ft=uint
      -v

  opcplc3:
    image: mcr.microsoft.com/iotedge/opc-plc:latest
    restart: unless-stopped
    hostname: opcplc3
    ports:
      - 50003:50000
      - 8083:8080
    command: >
      --aa
      --to
      --ph=opcplc3
      --pn=50000
      --sph
      --sn=5
      --sr=10
      --st=uint
      --fn=5
      --fr=1
      --ft=uint
      -v
      
  opcpublisher1:
    image: mcr.microsoft.com/iotedge/opc-publisher:2.9.4
    restart: unless-stopped
    command: -t=Mqtt
    environment:
      - MqttClientConnectionString=HostName=mosquitto;Port=1883;UseTls=False;Protocol=v5;NumberOfClientPartitions=1
      - PublishedNodesFile=/appdata/publisher.json
      - AutoAcceptUntrustedCertificates=True
      - MessagingMode=PubSub
      - MessageEncoding=Json
      - DefaultTransport=Mqtt
      - RootTopicTemplate=publisher1
      - MqttClientId=publisher1
      - BatchSize=1
      - BatchTriggerInterval=1
      - MqttProtocolVersion=v5
      - MqttBrokerUsesTls=False
    volumes:
      - ./publisher1.json:/appdata/publisher.json

  opcpublisher2:
    image: mcr.microsoft.com/iotedge/opc-publisher:2.9.4
    restart: unless-stopped
    command: -t=Mqtt
    environment:
      - MqttClientConnectionString=HostName=mosquitto;Port=1883;UseTls=False;Protocol=v5;NumberOfClientPartitions=1
      - PublishedNodesFile=/appdata/publisher.json
      - AutoAcceptUntrustedCertificates=True
      - MessagingMode=PubSub
      - MessageEncoding=Json
      - DefaultTransport=Mqtt
      - RootTopicTemplate=publisher2
      - MqttClientId=publisher2
      - BatchSize=1
      - BatchTriggerInterval=1
      - MqttProtocolVersion=v5
      - MqttBrokerUsesTls=False
    volumes:
      - ./publisher2.json:/appdata/publisher.json


